# Generated by Django 5.1.7 on 2025-03-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriptionplan_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
